mafile = []
mafile.append(17)
mafile.append(7)
mafile.append(23)
mafile.append(15)
mafile.append(12)
print(mafile)
print("je fait un push de 42")
mafile.append(42)
print(mafile)
monpop = mafile.pop(0)
print("je fait un pop et recois :", monpop)
monpop = mafile.pop(0)
print("je fait un pop et recois :", monpop)
print(mafile)
