mafile = []
mafile.insert(0, 17)
mafile.insert(0, 7)
mafile.insert(0, 23)
mafile.insert(0, 15)
mafile.insert(0, 12)
print(mafile)
print("je fais un push de 42")
mafile.insert(0, 42)
print(mafile)
monpop = mafile.pop(0)
print("je fais un pop et recois :", monpop)
monpop = mafile.pop(0)
print("je fais un pop et recois :", monpop)
print(mafile)
